## template:glesys
{{> users}}

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

write_files:
- content: |
    nodes:
       - address: {{params.hostname}}
         user: root
         role: [controlplane,etcd,worker]
         ssh_key_path: /root/.ssh/id_rsa
    addon_job_timeout: 120
  path: /root/cluster.yml
- content: |
    apiVersion: management.cattle.io/v3
    kind: NodeDriver
    metadata:
      annotations:
        lifecycle.cattle.io/create.node-driver-controller: "true"
        privateCredentialFields: password
      labels:
        cattle.io/creator: norman
      name: glesys
    spec:
      active: true
      builtin: false
      checksum: ""
      description: "GleSYS Cloud Node Driver"
      displayName: GleSYS
      externalId: ""
      uiUrl: ""
      url: https://github.com/glesys/docker-machine-driver-glesys/releases/download/v1.1.0/docker-machine-driver-glesys_linux-amd64
  path: /root/glesys-node-driver.yaml
- content: |
    spec:
      active: false
  path: /root/disable-driver.yaml
- content: |
    apiVersion: management.cattle.io/v3
    glesysConfig:
      apiKey: {{params.apiKey}}
      bandwidth: "100"
      campaignCode: ""
      cpu: "2"
      dataCenter: Falkenberg
      memory: "4096"
      platform: KVM
      project: {{params.project}}
      rootPassword: ""
      sshKeyPath: ""
      storage: "20"
      template: ubuntu-18-04
      usernameKvm: docker-machine
    kind: NodeTemplate
    metadata:
      annotations:
        ownerBindingsCreated: "false"
      name: glesys-base-template
      namespace: cattle-global-nt
    spec:
      displayName: KVM Base Template
      driver: glesys
      engineInstallURL: https://releases.rancher.com/install-docker/19.03.sh
      engineRegistryMirror: null
      useInternalIpAddress: true
  path: /root/glesys-node-template-kvm.yaml


runcmd:
  - ssh-keygen -f /root/.ssh/id_rsa -P "" -q
  - cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
  - curl https://releases.rancher.com/install-docker/18.09.sh | sh
  - wget https://github.com/rancher/rke/releases/download/v0.2.10/rke_linux-amd64
  - mv rke_linux-amd64 /usr/local/bin/rke
  - chmod +x  /usr/local/bin/rke
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - mv kubectl /usr/local/bin/
  - chmod +x  /usr/local/bin/kubectl
  - rke up --config /root/cluster.yml
  - export KUBECONFIG=/root/kube_config_cluster.yml
  - export HOME=/root
  - wget https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz
  - tar zxvf helm-v3.1.2-linux-amd64.tar.gz
  - mv linux-amd64/helm /usr/local/bin/
  - chmod +x  /usr/local/bin/helm
  - helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
  - kubectl create namespace cattle-system
  - kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml
  - kubectl create namespace cert-manager
  - helm repo add jetstack https://charts.jetstack.io
  - helm repo update
  - helm install   cert-manager jetstack/cert-manager   --namespace cert-manager   --version v0.12.0
  - kubectl -n cert-manager rollout status deploy/cert-manager
  - sleep 60
  - helm install rancher rancher-stable/rancher   --namespace cattle-system   --set hostname={{params.hostname}}   --set ingress.tls.source=letsEncrypt   --set letsEncrypt.email={{params.email}}
  - kubectl -n cattle-system rollout status deploy/rancher
  - kubectl patch nodedrivers.management.cattle.io -n cattle-system --type merge --patch "$(cat /root/disable-driver.yaml)" amazonec2
  - kubectl patch nodedrivers.management.cattle.io -n cattle-system --type merge --patch "$(cat /root/disable-driver.yaml)" digitalocean
  - kubectl patch nodedrivers.management.cattle.io -n cattle-system --type merge --patch "$(cat /root/disable-driver.yaml)" azure
  - kubectl patch nodedrivers.management.cattle.io -n cattle-system --type merge --patch "$(cat /root/disable-driver.yaml)" linode
  - kubectl patch nodedrivers.management.cattle.io -n cattle-system --type merge --patch "$(cat /root/disable-driver.yaml)" vmwarevsphere
  - kubectl patch kontainerdrivers.management.cattle.io -n cattle-system --type merge --patch "$(cat /root/disable-driver.yaml)" amazonelasticcontainerservice
  - kubectl patch kontainerdrivers.management.cattle.io -n cattle-system --type merge --patch "$(cat /root/disable-driver.yaml)" azurekubernetesservice
  - kubectl patch kontainerdrivers.management.cattle.io -n cattle-system --type merge --patch "$(cat /root/disable-driver.yaml)" googlekubernetesengine
  - kubectl patch kontainerdrivers.management.cattle.io -n cattle-system --type merge --patch "$(cat /root/disable-driver.yaml)" rancherkubernetesengine
  - kubectl apply -f  /root/glesys-node-driver.yaml  -n cattle-system
  - kubectl apply -f /root/glesys-node-template-kvm.yaml
