## template:glesys
#cloud-config
# Licensed under the CC0 1.0

{{>users}}

packages:
    - ca-certificates
    - tzdata
    - curl
locale: en_US.UTF-8
locale_configfile: /etc/default/locale
runcmd:
  - curl -o install-gitlab.sh https://raw.githubusercontent.com/glesys/one-click-installers/master/gitlab/install-gitlab.sh
  - chmod +x install-gitlab.sh
  - ./install-gitlab.sh {{params.bootstrapPassword}}
